### ISSUE TITLE
How to add support to ADSI16460?

### ISSUE THREAD

**Issue by sunchaothu** [tork-a/adi_driver#10]
I am considering to expend this great job to support adsi16460 imu sensor, but I am not sure what I should modify apart from include/adsi16460 ? Can anyone give me some advice? Thanks~

**Comment by 7675t** [comment]
Hi, thank you for your attention.
I found ADIS16460 have same function and identical resister mapping to ADIS16470.
So I believe you can use it with this package as it is, if you can wire it to the USB-ISS module properly. Please try it, and we will be very helped if you report the result. Thank you :smile:

**Comment by YihuanL** [comment]
So,  how about the result now? Could anybody share the code for adis16460? I am using the EVAL-ADIS2 system.
