### ISSUE TITLE
Add topic to publish temperature

### ISSUE THREAD

**Issue by Ktakao** [tork-a/adi_driver#14]
This is so useful ros package.

I tried, but there was no topic to publish temperature.
Looking at the specification of ADIS 16470, the register also includes temperature.
I think that it is more convenient as well as only use imu calibration.
Why don't you to add a topic to publish temperature?

**Comment by 7675t** [comment]
Thanks for the suggestion. Could you tell me your use-case in detail? Would you do temperature calibration by your self? Then is it OK to publish [the temperature message](http://docs.ros.org/melodic/api/sensor_msgs/html/msg/Temperature.html)  on /imu/temperature ?

**Comment by Ktakao** [comment]
I will not calibration by myself yet. I think taht other imu ros package include topic to publish temperature. I will use get temperature in robot housing. 

> Then is it OK to publish the temperature message on /imu/temperature ?

OK, Thank you for your response!

**Comment by 7675t** [comment]
Thank you for #17 !
