### ISSUE TITLE
ADIS16470/PCB Calibration

### ISSUE THREAD

**Issue by peterpanda01** [tork-a/adi_driver#21]
Is there a way to edit the biases for both the gyroscope and accelerometer from the ROS package. I am trying to edit the calibrate my ADIS16470 on ROS. I know there is a pull request for [bias estimation](https://github.com/tork-a/adi_driver/pull/20). I  want to know if that lets you edit the actual bias. Does it store the change on the program or does it save to the sensor's flash memory? How long does the change stay effective? Can I edit the bias for the accelerometer?

**Comment by 7675t** [comment]
- /imu/bias_estimate
  This service activate ADIS16470's internal bias estimation function. You should call this service after the IMU is placed steady for at least 40 seconds. The bias value of the gyro sensors are calcuarated as the average of the duration. The sensor value are obtained after it is substracted by the bias value. The bias value is not stored on the chip and reset when the powered up.

So, the bias value is volatile. Right now it supports only gyro, not acceleration sensors. And in general sensor's bias value is fluctuated through time, as the Allan distribution on the spec sheet says.

I think the best way for you is, to make an independent node to subscribe the raw IMU data and publish calibrated data to another topic. You can make it as it stores the bias value somewhere, calculate the acceleration bias, estimate  bias on line, whatever as you like.

**Comment by 7675t** [comment]
Of course you can add your own service to estimate the accel bias and functionality to edit the bias value in the sensor. PR is welcome. For now we don't have plan to do so.

**Comment by peterpanda01** [comment]
Thank you
