### ISSUE TITLE
ADIS

### ISSUE THREAD

**Issue by YeQuanPara** [tork-a/adi_driver#24]
Hi，Thanks for sharing, me I want to make some changes to fit ADIS16405, and I have a question about why this is 30,24 in your codes.
  int size = write(fd_, buff, 24);
 size = read(fd_, buff, 30);

**Comment by YeQuanPara** [comment]
Haha,OK, I'll look at the data manual. Thank you!

**Comment by YeQuanPara** [comment]
Hallo，I'm trying to understand your code and changing it to use my ADIS16405.But I can't uderstand why the register address doesn't correspond to the ADIS16470's datasheet.
I see the TEMP_OUT low address is 0x1C.Thank you!
https://github.com/YeQuanPara/adi_driver/blob/e2536bb86520373136e2a3439e99da3714ffb81f/src/adis16470.cpp#L341
https://github.com/YeQuanPara/adi_driver/blob/e2536bb86520373136e2a3439e99da3714ffb81f/src/adis16470.cpp#L340
https://github.com/YeQuanPara/adi_driver/blob/e2536bb86520373136e2a3439e99da3714ffb81f/src/adis16470.cpp#L353

**Comment by YeQuanPara** [comment]
Hallo, when read the temp_out,why the address is 0x00, I see TEMP_OUT low address is 0x1C in the datasheet. Thank [you!]https://github.com/tork-a/adi_driver/blob/e2536bb86520373136e2a3439e99da3714ffb81f/src/adis16470.cpp#L353

**Comment by 7675t** [comment]
Hi, SPI interface receive the address first, and send the data in next sync. So 0x00 is a dummy address.

Please read through the datasheet. It explains almost everything.

**Comment by YeQuanPara** [comment]
OK，Thank you！
