### ISSUE TITLE
ERROR: cannot launch node of type [imu_filter_madgwick/imu_filter_node]: imu_filter_madgwick

### ISSUE THREAD

**Issue by YihuanL** [tork-a/adi_driver#31]
Hi,
I have tested this pakage  on ADIS16460 connected to USB-ISS and got the belowing errors:
ERROR: cannot launch node of type [imu_filter_madgwick/imu_filter_node]: imu_filter_madgwick
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/ivan/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share

Do you have and idea about that?
Thanks in advance.

**Comment by YihuanL** [comment]
fixed when install ROS pakage of  imu_tools from http://wiki.ros.org/imu_filter_madgwick

**Comment by tugbakara** [comment]
Hi, I cannot launch adis16470_node instead imu_filter_madgwick
